package:
  name: hicup
  version: "0.5.9"

source:
  url: http://www.bioinformatics.babraham.ac.uk/projects/hicup/hicup_v0.5.9.tar.gz
  md5: 58702fb9c7f2f4887f4113bf284d1b98

requirements:
  run:
    - perl
    - r-base
    - samtools >=0.1.18
    - bowtie
    - bowtie2
about:
  home: http://www.bioinformatics.babraham.ac.uk/projects/hicup/
  license: GPL 3.0